'''Problem

In DNA strings, symbols 'A' and 'T' are complements of each other, as are 'C' and 'G'.

The reverse complement of a DNA string s
is the string sc formed by reversing the symbols of s

, then taking the complement of each symbol (e.g., the reverse complement of "GTCA" is "TGAC").

Given: A DNA string s

of length at most 1000 bp.

Return: The reverse complement sc of s.'''

dna_strand = 'CTCCATAAGTTATTCCTCAGACTGTCGAGTCACTGGTACATGCTTGGACCATGCAATGCAACAGGCTTGGACGTTGTAAATCAGCCTTGTCAAACTGTATTCCGATCGTCTATTAGTATCCTCGGTACGGTGAAGCGAGCAATGAGCCCTAAATCACTCCCTGGAACATGCATAATTGCGATGTAAGCTGAGACGAAACCTATATTTACAAGCGGAGCATTCGACCGGGCCTCCCGTCCCACAGCTGTTGCTCCGCCGTTCGCTGCGCGTAATAATTATGTCTTCAATTCCTCCGCGGAAATCTCGGAGATCATTTCTTCCAAGACCACATTGCTATACACCGCCGCATATTGAGAACGCTTCTTCATATACACTTTCGATGGCGCATTACTTAATGATTGAAGAATGCCTTGTCAATGTTTACCTCTTTATGCGTGCGGATACGGCTTTAGTAAAACGTAGTCGACGATATTAGTACATCACAAATTTGAGATGACTGTGCAACGCCTTAGATGAAATGACCTTCCTAGTGACTAAGAGACAGAATCGATTAAATATATTTACATACCCTATGACACCTAATCAGAACGCACAATAGGCTGACCTAACTGATAAGTTAGCAATGGGCCTACTGGAGATAACGCTAATTGTCTAACGATGTGTCGTCGTTCAAACACATTAAGGTGCGCCTCATAACAGTGGCAAAGGGTATACGACGTGGCAATAGGTTGGGATAAGTAACGTGAGCGTAAACATATCTTTTCGGTCTAGCTAACTACTGTGGTGTCTCGCCGTACAGGATCCCCCGACGGCTGCATGAAACAT'
dna_dict = {'A' : 'T',
            'T' : 'A',
            'G' : 'C',
            'C' : 'G'}
rev_dna = ''
for x in dna_strand[::-1]:
    rev_dna += dna_dict[x]

print(rev_dna)